### ISSUE TITLE
The binary should be named `nh`

### ISSUE THREAD

**Issue by thecaralice** [ToyVo/nh_darwin#14]
nh_darwin is fully compatible with `nh`, it is not a different project but just the original project with several patches, nh_darwin should not conflict with nh is these are not supposed to be installed together. Please rename to `nh`.

**Comment by bestlem** [comment]
The issue I think is that the original nh does run on macOS - it will manage home-manager at least.
How do you differentiate the two?

**Comment by thecaralice** [comment]
I would differentiate between the packages, but why would I need to differentiate between the actual binaries if I only have one of them installed at any moment? Like GCC linker and LLVM linker are both `/bin/ld` despite having completely different implementations, and Vim xxd and standalone xxd are both `/bin/xxd` despite having different origins.

**Comment by ToyVo** [comment]
Originally it wasn't renamed but people wanted it. 

https://github.com/ToyVo/nh_darwin/issues/6

Additionally if you use the modules provided by the flake you can enable programs.nh.alias to create a symlink to nh

**Comment by thecaralice** [comment]
Well I think the decision to rename the tool was rather rash and after reading both #6 and LnL7/nix-darwin#942 I still don't see any issue caused by nh_darwin binary being called `nh`.

**Comment by ToyVo** [comment]
I'm not disagreeing with you. Being that I did that change "rashly" I would appreciate anyone else chiming in so I don't do it again.

**Comment by thecaralice** [comment]
I should note that this description is somewhat ironic
<img width="473" alt="image" src="https://github.com/user-attachments/assets/c4c83b34-3b4e-491c-a7bd-84d4d424c863">

**Comment by ToyVo** [comment]
anybody who comes across this and would like to provide input please contribute here: https://github.com/ToyVo/nh_darwin/discussions/18
I am unsure of when I will end the poll, I can't imagine It'll get a ton of votes

**Comment by ToyVo** [comment]
Mentioned in the discussion but the results were in favor of putting the binary name back to nh, including my own preference. But the flake will have both a nh and a nh_darwin package defined, the nh_darwin will simply be a symlink to nh.
